Implementation of responsive DOM
LambdaTest/smartui-cli pull request #138
Opened 2024-10-08 10:10 UTC by parthlambdatest

2024-10-08 12:41 UTC, sushobhit-lt commented on src/lib/processSnapshot.ts
> +        const browsers = webConfig.browsers ?? this.ctx.config.web?.browsers ?? ["chrome", "edge", "firefox", "safari"];
@parthlambdatest Please use static constants for browsers

2024-10-08 12:43 UTC, sushobhit-lt commented on src/tasks/processSnapshot.ts
> +                    console.log("started after processing because of deferuploads")
Use ctx.log.info(""), here

2024-10-08 12:46 UTC, sushobhit-lt commented on src/lib/processSnapshot.ts
> +            const orientation = config.mobile.orientation || "portrait";  // Default to portrait if not provided
Use  `"portrait"` as a constant , its used 6 time in this file

2024-10-08 12:52 UTC, sushobhit-lt commented on src/lib/processSnapshot.ts
> +                const variant = `${snapshot.name}_${device}_${orientation}_${fullPage ? 'fullPage' : 'noFullPage'}`;
Please use static constants for browsers `'fullPage'`  `'noFullPage'` values, its used 4 times in same file

2024-10-09 07:48 UTC, sushobhit-lt approved these changes

2024-10-16 12:46 UTC, pinanks requested changes

2024-10-16 12:46 UTC, pinanks commented on src/lib/processSnapshot.ts
> +    enqueue(item: Snapshot, start: boolean): void {
This is redundant. Use ctx.config which is already in the queue.

2024-10-16 12:48 UTC, pinanks commented
Also, add the Queue in a separate file called `snapshotQueue.ts`

2024-10-17 08:19 UTC, pinanks approved these changes

2024-10-17 08:19 UTC, merged